---
title: "Maps_and_plots"
author: "Becca Storey"
date: "12/6/2018"
output: html_document
---


```{r setup, include=FALSE}
library(httr)
library(tidyverse)
library(ggmap)
```

```{r}
new_york_final <- read_csv("new_york_final.csv")
seattle_final <- read_csv("seattle_final.csv")
houston_final <- read_csv("houston_final.csv")
san_francisco_final <- read_csv("san_francisco_final.csv")
```

```{r}
read_csv("new_york_final.csv")
```


```{r}
foo2 <- airbnb.df$AboutListing[5]
str_detect(foo2, "[Pp]ublic [Tt]ransportation")

airbnb.df <- airbnb.df %>%
  mutate(pub_trans = str_detect(AboutListing, "[Pp]ublic [Tt]ransportation"))
  airbnb.df %>% group_by(pub_trans) %>% tally()

ggplot(airbnb.df %>%
         filter(Price < 1500), 
aes(x = pub_trans, y = Price)) +
  geom_boxplot() +
  labs(
    title = paste("Public Transportation and Price"),
    x = "Access to Public Transportation",
    y = "Price")
```

## Category Analysis for San Francisco 
```{r}
san_francisco <- san_francisco_final %>%
mutate(Coffee = str_detect(san_francisco_final$categories,"[Cc]offee"),
       Wine = str_detect(san_francisco_final$categories,"[Ww]ine"),
       Cocktail = str_detect(san_francisco_final$categories,"[Cc]ocktail"),
       Brunch = str_detect(san_francisco_final$categories,"[Bb]runch"),
       Brewery = str_detect(san_francisco_final$categories,"[Bb]reweries"),
       Bakery = str_detect(san_francisco_final$categories,"[Bb]akeries"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Coffee)) +
  labs(
    title = paste("Coffee Bars in San Francisco"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Wine)) + 
  labs(
    title = paste("Wine Bars in San Francisco"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Cocktail)) +
  labs(
    title = paste("Cocktail Bars in San Francisco"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Brunch)) +
  labs(
    title = paste("Brunch in San Francisco"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Brewery)) +
  labs(
    title = paste("Breweries in San Francisco"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Bakery)) +
  labs(
    title = paste("Bakeries in San Francisco"))

```

## Asian across cities

```{r}

san_francisco <- san_francisco_final %>%
  mutate(Asian = str_detect(san_francisco_final$categories,"[Vv]ietnamese|[Tt]ai|[Cc]inese|[Jj]apanese|[Cc]ambodian"))
new_york_city <- new_york_final %>%
mutate(Asian = str_detect(houston_final$categories,"[Vv]ietnamese|[Tt]ai|[Cc]inese|[Jj]apanese|[Cc]ambodian"))
houston <- houston_final %>%
  mutate(Asian = str_detect(houston_final$categories, "[Vv]ietnamese|[Tt]ai|[Cc]inese|[Jj]apanese|[Cc]ambodian"))
seattle <- seattle_final %>%
  mutate(Asian = str_detect(seattle_final$categories, "[Vv]ietnamese|[Tt]ai|[Cc]inese|[Jj]apanese|[Cc]ambodian"))

ggplot(data = san_francisco) +
  geom_bar(mapping = aes(x = Asian)) +
  labs(
    title = paste("Asian in San Francisco"))

ggplot(data = new_york_city) +
  geom_bar(mapping = aes(x = Asian)) +
  labs(
    title = paste("Asian in New York City"))

ggplot(data = houston) +
  geom_bar(mapping = aes(x = Asian)) +
  labs(
    title = paste("Asian in Houston"))

ggplot(data = seattle) +
  geom_bar(mapping = aes(x = Asian)) +
  labs(
    title = paste("Asian in Seattle"))
```





##Count versus Price 
```{r}
count_price_new_york <- ggplot(data = new_york_final) +
  geom_bar(mapping = aes(x = price)) +
  labs(
    title = paste("Price"),
    x = "Price",
    y = "Count")
count_price_seattle <- ggplot(data = seattle_final) +
  geom_bar(mapping = aes(x = price)) +
  labs(
    title = paste("Price"),
    x = "Price",
    y = "Count")
count_price_houston <- ggplot(data = houston_final) +
  geom_bar(mapping = aes(x = price)) +
  labs(
    title = paste("Price"),
    x = "Price",
    y = "Count")
count_price_sanfran <- ggplot(data = san_francisco_final) +
  geom_bar(mapping = aes(x = price)) +
  labs(
    title = paste("Price"),
    x = "Price",
    y = "Count")

print(count_price_new_york)
print(count_price_seattle)
print(count_price_houston)
print(count_price_sanfran)
```


## Count Versus Rating 
```{r}
count_rating_new_york <- ggplot(data = new_york_final ) +
  geom_bar(mapping = aes(x = Rating)) +
  labs(
    title = paste("Rating"),
    x = "Rating",
    y = "Count")
count_rating_seattle <- ggplot(data = seattle_final ) +
  geom_bar(mapping = aes(x = Rating)) +
  labs(
    title = paste("Rating"),
    x = "Rating",
    y = "Count")
count_rating_houston <- ggplot(data = houston_final ) +
  geom_bar(mapping = aes(x = Rating)) +
  labs(
    title = paste("Rating"),
    x = "Rating",
    y = "Count")
count_rating_sanfran <- ggplot(data = san_francisco_final ) +
  geom_bar(mapping = aes(x = Rating)) +
  labs(
    title = paste("Rating"),
    x = "Rating",
    y = "Count")

print(count_rating_new_york)
print(count_rating_seattle)
print(count_rating_houston)
print(count_rating_sanfran)
```

## Number of Reviews 
```{r}
count_review_new_york <- ggplot(data = new_york_final) +
  geom_histogram(mapping = aes(x = review_count), binwidth = 500) +
  coord_cartesian(xlim = c(0, 8000)) +
  labs(
    title = paste("Reviews"),
    x = "Reviews",
    y = "Count")
count_review_seattle <- ggplot(data = seattle_final) +
  geom_histogram(mapping = aes(x = review_count), binwidth = 500) +
  coord_cartesian(xlim = c(0, 8000))  +
  labs(
    title = paste("Reviews"),
    x = "Reviews",
    y = "Count")
count_review_houston <- ggplot(data = seattle_final) +
  geom_histogram(mapping = aes(x = review_count), binwidth = 500) +
  coord_cartesian(xlim = c(0, 8000))  +
  labs(
    title = paste("Reviews"),
    x = "Reviews",
    y = "Count")
count_review_sanfran <-  ggplot(data = san_francisco_final) +
  geom_histogram(mapping = aes(x = review_count), binwidth = 500) +
  coord_cartesian(xlim = c(0, 8000))  +
  labs(
    title = paste("Reviews"),
    x = "Reviews",
    y = "Count")

print(count_review_new_york)
print(count_review_seattle)
print(count_review_houston)
print(count_review_sanfran)
```

## Rating Versus Review 
```{r}
rating_review_new_york <- ggplot(data = new_york_final) +
  geom_boxplot(mapping = aes(x = as.factor(Rating), y = review_count))  +
  labs(
    title = paste("Ratings by Review"),
    x = "Rating",
    y = "Number of Reviews")
rating_review_seattle <- ggplot(data = seattle_final) +
  geom_boxplot(mapping = aes(x = as.factor(Rating), y = review_count))  +
  labs(
    title = paste("Ratings by Review"),
    x = "Rating",
    y = "Number of Reviews")
rating_review_houston <- ggplot(data = houston_final) +
  geom_boxplot(mapping = aes(x = as.factor(Rating), y = review_count))  +
  labs(
    title = paste("Ratings by Review"),
    x = "Rating",
    y = "Number of Reviews")
rating_review_sanfran <- ggplot(data = san_francisco_final) +
  geom_boxplot(mapping = aes(x = as.factor(Rating), y = review_count))  +
  labs(
    title = paste("Ratings by Review"),
    x = "Rating",
    y = "Number of Reviews")

print(rating_review_new_york)
print(rating_review_seattle)
print(rating_review_houston)
print(rating_review_sanfran)
```


## Rating Versus Price
```{r}
rating_price_new_york <- ggplot(data = new_york_final) +
  geom_violin(mapping = aes(x = as.factor(price), y = Rating))  +
  labs(
    title = paste("Price by Rating"),
    x = "Price",
    y = "Rating")
rating_price_seattle <- ggplot(data = seattle_final) +
  geom_violin(mapping = aes(x = as.factor(price), y = Rating))  +
  labs(
    title = paste("Price by Rating"),
    x = "Price",
    y = "Rating")
rating_price_houston <- ggplot(data = houston_final) +
  geom_violin(mapping = aes(x = as.factor(price), y = Rating))  +
  labs(
    title = paste("Price by Rating"),
    x = "Price",
    y = "Rating")
rating_price_sanfran <- ggplot(data = san_francisco_final) +
  geom_violin(mapping = aes(x = as.factor(price), y = Rating))  +
  labs(
    title = paste("Price by Rating"),
    x = "Price",
    y = "Rating")

print(rating_price_new_york)
print(rating_price_seattle)
print(rating_price_houston)
print(rating_price_sanfran)
```


## Prive Versus Review
```{r}
price_review_new_york <- ggplot(data = new_york_final) +
  geom_boxplot(mapping = aes(x = as.factor(price), y = review_count))  +
  labs(
    title = paste("Price by Reviews"),
    x = "Price",
    y = "Number of Reviews")
price_review_seattle <- ggplot(data = seattle_final) +
  geom_boxplot(mapping = aes(x = as.factor(price), y = review_count)) +
  labs(
    title = paste("Price by Reviews"),
    x = "Price",
    y = "Number of Reviews")
price_review_houston <- ggplot(data = houston_final) +
  geom_boxplot(mapping = aes(x = as.factor(price), y = review_count)) +
  labs(
    title = paste("Price by Reviews"),
    x = "Price",
    y = "Number of Reviews")
price_review_sanfran <- ggplot(data = san_francisco_final) +
  geom_boxplot(mapping = aes(x = as.factor(price), y = review_count)) +
  labs(
    title = paste("Price by Reviews"),
    x = "Price",
    y = "Number of Reviews")

print(price_review_new_york)
print(price_review_seattle)
print(price_review_houston)
print(price_review_sanfran)
```


##Maps

## Seattle
```{r}
qmplot(longitude, latitude, data = seattle_final,
       colour = I('red'), size = I(1), darken = ,1)

seattle_box <- c(left = min(seattle_final$longitude), bottom =
min(seattle_final$latitude), right = max(seattle_final$longitude), top = max(seattle_final$latitude))

seattlemap <- get_stamenmap(seattle_box, zoom = 12, maptype = "terrain") 
ggmap(seattlemap)

ggmap(seattlemap) +
  geom_point(data = seattle_final, aes(x = longitude, y = latitude))
```


## New York City 
```{r}
qmplot(longitude, latitude, data = new_york_final,
       colour = I('red'), size = I(1), darken = ,1)

nyc_box <- c(left = min(new_york_final$longitude), bottom =
min(new_york_final$latitude), right = max(new_york_final$longitude), top = max(new_york_final$latitude))

nycmap <- get_stamenmap(nyc_box, zoom = 12, maptype = "terrain") 
ggmap(nycmap)

ggmap(nycmap) +
  geom_point(data = new_york_final, aes(x = longitude, y = latitude))
```

##Houston 
```{r}
qmplot(longitude, latitude, data = houston_final,
       colour = I('red'), size = I(1), darken = ,1)

houston_box <- c(left = min(houston_final$longitude), bottom =
min(houston_final$latitude), right = max(houston_final$longitude), top = max(houston_final$latitude))

houstonmap <- get_stamenmap(nyc_box, zoom = 12, maptype = "terrain") 
ggmap(houstonmap)

ggmap(houstonmap) +
  geom_point(data = houston_final, aes(x = longitude, y = latitude))
```


```{r}
qmplot(longitude, latitude, data = san_francisco_final,
       colour = I('red'), size = I(1), darken = ,1)

sanfran_box <- c(left = min(san_francisco_final$longitude), bottom =
min(san_francisco_final$latitude), right = max(san_francisco_final$longitude), top = max(san_francisco_final$latitude))

sanfranmap <- get_stamenmap(sanfran_box, zoom = 12, maptype = "terrain") 
ggmap(sanfranmap)

ggmap(sanfranmap) +
  geom_point(data = san_francisco_final, aes(x = longitude, y = latitude))
```


